modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/Cyber1551/Fluidic-Arm/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[7.4.1,)"
# Load AFTER GregTech so its classes exist when this mod registers its cover
ordering = "AFTER"
side = "BOTH"
